name: Build and Test Package

on:
  workflow_run:
    workflows: ["CI Tests"]
    types:
      - completed
  # Only publish on release tags
  release:
    types: [published]

jobs:
  codeBuild:
    name: 'Build Code with Hatch'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Workflow Chain Status
        run: |
          echo "🔄 **Workflow Dependency Chain Status**" >> $GITHUB_STEP_SUMMARY
          echo "1. ✅ Documentation Build - Completed Successfully" >> $GITHUB_STEP_SUMMARY  
          echo "2. ✅ CI Tests - Completed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "3. 🚀 **Build and Package** - Running Now" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install hatch
      - name: Build the project
        run: |
          hatch build

  lintingChecks:
    name: 'Run Linting Checks'
    runs-on: ubuntu-latest
    needs: codeBuild
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install hatch
      - name: Create Hatch environment
        run: |
          hatch env create
      - name: Build the project
        run: |
          hatch build
      - name: Run isort
        run: |
          echo "Running isort..."
          hatch run dev:isort ./lock_and_key --check-only --diff
      - name: Run black
        run: |
          echo "Running black..."
          hatch run dev:black ./lock_and_key --check --diff
      - name: Run flake8
        run: |
          echo "Running flake8..."
          hatch run dev:flake8 ./lock_and_key

  mypyChecks:
    name: 'Run MyPy Checks'
    runs-on: ubuntu-latest
    needs: lintingChecks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install hatch
      - name: Build the project
        run: |
          hatch build
      - name: Create Hatch environment
        run: |
          hatch env create
      - name: Run mypy
        run: |
          echo "Running mypy..."
          hatch run dev:mypy ./lock_and_key

  unitTests:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    needs: mypyChecks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install hatch
      - name: Build the project
        run: |
          hatch build
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          hatch test

  publishCode:
    name: 'Build and Publish to PyPI'
    runs-on: ubuntu-latest
    needs: unitTests
    if: github.event_name == 'release'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Workflow Chain Status
      run: |
        echo "🔄 **Workflow Dependency Chain Status**" >> $GITHUB_STEP_SUMMARY
        echo "1. ✅ Documentation Build - Completed Successfully" >> $GITHUB_STEP_SUMMARY  
        echo "2. ✅ CI Tests - Completed Successfully" >> $GITHUB_STEP_SUMMARY
        echo "3. 🚀 **Build and Package** - Running Now" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    
    - name: Build package with Hatch
      run: |
        hatch build
    
    - name: Verify build contents
      run: |
        echo "Contents of dist directory:"
        ls -la dist/
        echo "Checking package metadata:"
        python -m pip install twine
        twine check dist/*
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install twine
        twine upload dist/*
    
    - name: Final Workflow Summary
      run: |
        echo "🎉 **Workflow Chain Completed Successfully!**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ 1. Documentation Build - Completed" >> $GITHUB_STEP_SUMMARY  
        echo "✅ 2. CI Tests - Completed" >> $GITHUB_STEP_SUMMARY
        echo "✅ 3. Build and Package - Completed" >> $GITHUB_STEP_SUMMARY
        echo "🚀 4. Published to PyPI - Success!" >> $GITHUB_STEP_SUMMARY